disabled_rules:
  - file_length
  - function_body_length
  - type_body_length
  - todo
  - trailing_whitespace
  - unused_closure_parameter

opt_in_rules:
  - force_unwrapping
  - closure_spacing
  - collection_alignment
  - contains_over_filter_is_empty
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_parameters
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - strong_iboutlet
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment
  - yoda_condition
  - missing_docs

force_unwrapping:
  severity: error
  
analyzer_rules:
  - unused_import
  - explicit_self

force_cast: error
force_try: error


line_length:
  warning: 150
  error: 180
  ignores_comments: true
  ignores_urls: true

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 1
  max_length: 40

cyclomatic_complexity:
  warning: 10
  error: 15

redundant_type_annotation:
  consider_default_literal_types_redundant: true

missing_docs:
  public: warning
  open: warning

excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - Tests/Generated
  - Generated
  - Fastlane
  - R.generated.swift
  - Package.swift

included:
  - "**/*.swift"

custom_rules:
  no_direct_ui_in_viewmodel:
    included: "Sources/*ViewModel*"
    regex: "(UI|NS)(View|Label|Button|Image)"
    message: "View models must not contain UI references"
    severity: warning
