disabled_rules:
  - file_length
  - function_body_length
  - type_body_length
  - todo

opt_in_rules:
  - anyobject_protocol
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_is_empty
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_parameters
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - explicit_top_level_acl
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - trailing_closure
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment
  - vertical_whitespace_between_cases
  - yoda_condition

force_cast: error
force_try: error
implicitly_unwrapped_optional: error
prohibited_super_call: error

line_length:
  warning: 150
  error: 180
  ignores_comments: true
  ignores_urls: true

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 3
  max_length: 40

closure_body_length:
  warning: 20
  error: 30

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  warning: 3
  error: 4

redundant_type_annotation:
  consider_default_literal_types_redundant: true

trailing_comma:
  mandatory_comma: true

missing_docs:
  public: warning
  open: warning

excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - Tests/Generated
  - Generated
  - Fastlane
  - R.generated.swift
  - Package.swift

included:
  - "**/*.swift"

custom_rules:
  no_direct_ui_in_viewmodel:
    included: "Sources/*ViewModel*"
    regex: "(UI|NS)(View|Label|Button|Image)"
    message: "View models must not contain UI references"
    severity: warning
