name: Todoist

options:
  bundleIdPrefix: com.artkriukov
  deploymentTarget:
    iOS: "15.0"
  defaultConfig: Production

configs:
  Debug: debug
  Production: release

targets:
  Todoist:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Todoist/App
      - path: Todoist/Models
      - path: Todoist/CustomUI
      - path: Todoist/Helpers
      - path: Todoist/Modules
      - path: Todoist/Resources
    resources:
      - path: Todoist/Resources

    settings:
      base:
        INFOPLIST_FILE: Todoist/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.artkriukov.Todoist
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
    scheme:
      environmentVariables:
        DYLD_PRINT_STATISTICS: "1"
